[build]
  base = "/"
  command = "cd platform && NODE_ENV=production npm install && CI=false npm run build"
  publish = "platform/build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
