[build]
  base = "/"
  command = "cd platform && NODE_ENV=production npm install --verbose && CI=false npm run build"
  publish = "platform/build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-audit --production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
